# Generated by Django 6.0.1 on 2026-08-05 00:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('event_type', models.CharField(choices=[('wedding', 'Mariage'), ('birthday', 'Anniversaire'), ('collation', 'Collation'), ('baptism', 'Bapteme'), ('conference', 'Conference'), ('family_party', 'Fete familiale'), ('graduation', 'Remise de diplome'), ('meeting', 'Reunion'), ('other', 'Autre')], default='other', max_length=32)),
                ('description', models.TextField(blank=True)),
                ('host_names', models.CharField(help_text='Names shown in the WhatsApp invitation.', max_length=255)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='events/covers/')),
                ('event_date', models.DateField()),
                ('event_time', models.TimeField()),
                ('address', models.CharField(max_length=255)),
                ('google_maps_url', models.URLField(blank=True)),
                ('detailed_program', models.TextField(blank=True)),
                ('dress_code', models.CharField(blank=True, max_length=255)),
                ('welcome_message', models.TextField(blank=True)),
                ('rsvp_deadline', models.DateField(blank=True, null=True)),
                ('max_guests', models.PositiveIntegerField(default=100)),
                ('background_music', models.FileField(blank=True, null=True, upload_to='events/music/')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publie'), ('archived', 'Archive')], default='draft', max_length=16)),
                ('allow_multiple_entries', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-event_date', '-event_time'],
            },
        ),
        migrations.CreateModel(
            name='EventProgram',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_items', to='events.event')),
            ],
            options={
                'ordering': ['sort_order', 'start_at'],
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='events/gallery/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('is_organizer_photo', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_items', to='events.event')),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('primary_color', models.CharField(default='#0D0D0D', max_length=7)),
                ('secondary_color', models.CharField(default='#C1121F', max_length=7)),
                ('accent_color', models.CharField(default='#E5383B', max_length=7)),
                ('text_color', models.CharField(default='#F8FAFC', max_length=7)),
                ('glass_opacity', models.DecimalField(decimal_places=2, default=0.18, max_digits=3)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='theme', to='events.event')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['owner', 'status'], name='events_even_owner_i_cf96c4_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['event_date', 'event_type'], name='events_even_event_d_4622cf_idx'),
        ),
    ]
