# Generated by Django 6.0.1 on 2026-08-05 00:11

import apps.invitations.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(default=apps.invitations.models.generate_personal_token, editable=False, max_length=12, unique=True)),
                ('delivery_status', models.CharField(choices=[('pending', 'En attente'), ('generated', 'Generee'), ('sent', 'Envoyee'), ('opened', 'Ouverte')], default='pending', max_length=16)),
                ('whatsapp_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='events.event')),
                ('guest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invitation', to='guests.guest')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event', 'delivery_status'], name='invitations_event_i_4d0745_idx')],
            },
        ),
    ]
