# Generated by Django 6.0.1 on 2026-08-05 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='last_delivery_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='invitation',
            name='provider',
            field=models.CharField(choices=[('manual', 'Lien manuel'), ('whatsapp_cloud', 'WhatsApp Cloud API')], default='manual', max_length=32),
        ),
        migrations.AddField(
            model_name='invitation',
            name='provider_message_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='delivery_status',
            field=models.CharField(choices=[('pending', 'En attente'), ('generated', 'Generee'), ('sent', 'Envoyee'), ('opened', 'Ouverte'), ('failed', 'Echec')], default='pending', max_length=16),
        ),
    ]
