# Generated by Django 6.0.1 on 2026-08-05 00:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255)),
                ('whatsapp_number', models.CharField(max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('category', models.CharField(choices=[('vip', 'VIP'), ('family', 'Famille'), ('friends', 'Amis'), ('colleagues', 'Collegues'), ('witnesses', 'Temoins'), ('parents', 'Parents'), ('other', 'Autres')], default='other', max_length=32)),
                ('allowed_companions', models.PositiveIntegerField(default=0)),
                ('reserved_table', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('sent', 'Invitation envoyee'), ('present', 'Present'), ('absent', 'Absent'), ('arrived', 'Arrive'), ('scanned', 'QR Scanne')], default='pending', max_length=16)),
                ('invited_at', models.DateTimeField(blank=True, null=True)),
                ('arrived_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='events.event')),
            ],
            options={
                'ordering': ['full_name'],
                'indexes': [models.Index(fields=['event', 'status'], name='guests_gues_event_i_80021b_idx'), models.Index(fields=['event', 'category'], name='guests_gues_event_i_5814eb_idx')],
                'constraints': [models.UniqueConstraint(fields=('event', 'whatsapp_number'), name='unique_guest_phone_per_event')],
            },
        ),
    ]
