# Generated by Django 6.0.1 on 2026-08-05 00:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RSVP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('response', models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Je serai present'), ('declined', 'Je ne pourrai pas venir')], default='pending', max_length=16)),
                ('companion_count', models.PositiveIntegerField(default=0)),
                ('guest_message', models.TextField(blank=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvps', to='events.event')),
                ('guest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rsvp', to='guests.guest')),
            ],
            options={
                'verbose_name': 'RSVP',
                'verbose_name_plural': 'RSVPs',
                'indexes': [models.Index(fields=['event', 'response'], name='rsvp_rsvp_event_i_6df6ca_idx')],
            },
        ),
    ]
