# Generated by Django 6.0.1 on 2026-08-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsvp',
            name='drink_preference',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]