# Generated by Django 6.0.1 on 2026-08-05 00:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='qr-codes/')),
                ('is_active', models.BooleanField(default=True)),
                ('last_scanned_at', models.DateTimeField(blank=True, null=True)),
                ('scan_count', models.PositiveIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_codes', to='events.event')),
                ('guest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qrcode', to='guests.guest')),
            ],
            options={
                'verbose_name': 'QR code',
                'verbose_name_plural': 'QR codes',
            },
        ),
    ]
